spring:
  application:
    name: batch-service
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:db;MODE=MYSQL
    username: sa
    password:
#    meta:
#      hikari:
#        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#        url: jdbc:log4jdbc:mysql://localhost:3306/meta
#        username: batch
#        password: batch
#    domain:
#      hikari:
#        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#        url: jdbc:log4jdbc:mysql://localhost:3306/domain
#        username: batch
#        password: batch
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#      dialect: org.hibernate.dialect.MySQL8Dialect
#  sql:
#    init:
#      mode: always
  batch:
    job:
      enabled: true
#    jdbc:
#      initialize-schema: always