DROP TABLE IF EXISTS tb_product;

CREATE TABLE tb_product (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    product_name VARCHAR(255) NOT NULL,
    product_price INT NOT NULL
);

DROP TABLE IF EXISTS tb_new_product;

CREATE TABLE tb_new_product (
    product_id BIGINT NOT NULL PRIMARY KEY,
    product_name VARCHAR(255) NOT NULL,
    product_price INT NOT NULL
);